name: Build and Deploy Spring Boot App to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Deploy to EC2
        uses: ./.github/actions/deploy-springboot
        with:
          ec2-host: ${{ secrets.EC2_HOST }}
          ec2-user: ${{ secrets.EC2_USER }}
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
          jar-path: target/*.jar
